
submit:
	sbatch submit.sh

main:
	g++-7 main.cpp -fopenmp -o main.out
	./main.out

ceshi:
	g++-7 ceshi.cpp -fopenmp -o ceshi.out
	./ceshi.out

maino:
	g++-7 maino.cpp -fopenmp -o maino.out
	./maino.out	

mainc:
	g++ mainc.cpp -fopenmp -o mainc.out
	./mainc.out	

